### ISSUE TITLE
load_dotenv refers to .env in examples folder instead of root

### ISSUE THREAD

**Issue by SanderLeung** [pamelafox/pgvector-playground#4]
It is slightly confusing based on the README when initially creating the .env file. The first assumption would be to create this file in the root directory as that is where the .env.devcontainer file is, and is common practice, but the example files all refer to a .env file relative to the examples directory.

**Comment by pamelafox** [comment]
load_dotenv will also look for that .env file in the root, did it not work when you put it there? That's where I put mine. I can also leave the ".env" parameter out of the load_dotenv call entirely, and it'll do the same thing, look for it in a few places, but am not sure if that's clearer.

**Comment by pamelafox** [comment]
Okay, let's just remove the .env then and rely on the parameterless version, since thats more flexible. PR welcome
