### ISSUE TITLE
postgres db does not have vector extension initialized for some files

### ISSUE THREAD

**Issue by SanderLeung** [pamelafox/pgvector-playground#5]
Ran into this error initially running an example file: ```sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "vector" does not exist```

Running ```CREATE EXTENSION vector;``` in the local database resolved the issue. I am unsure if this only applies to the codespaces local db, or whether a devcontainer solution would be applicable, or if it should just be something mentioned in the README.

**Comment by SanderLeung** [comment]
On closer inspection of the example files, it appears most actually have the line ```CREATE EXTENSION IF NOT EXISTS vector```. This was an in issue with the ```sqlmodel_items.py``` file, and possibly ```sqlalchemy_async.py``` if any of the other files with that line were not run first.

**Comment by pamelafox** [comment]
Yep, you're right! I fixed that in a related repo (https://github.com/Azure-Samples/azure-postgres-pgvector-python/) but not this one. Fixing now.
